title PCのみを使う場合

participant Board as b
participant PrintController as pc
participant プリンタ as pt

pc -> pc: 端末起動

== 未印刷伝票印刷 ==
pc -> b: FetchBoard API
b -> pc: BoardObjects
pc -> pc: キャンセルされた注文を取得
note left
    ・kitchen_statusがcanceled
end note

pc -> pc: 伝票未印刷の注文を取得
note left
    ・kitchen_statusがcanceled以外
end note

...

pc -> pc: 未印刷キャンセル伝票印刷
loop キャンセル注文分
    alt 単票印刷する場合
        loop 注文明細分
            pc -> pt: キャンセル単票印刷
        end
    end
    alt 複票印刷する場合
        pc -> pt: キャンセル複票印刷
    end
    pc -> b: 注文BoardObjectDelete
end

pc -> pc: 未印刷伝票印刷
loop 注文分
    alt 単票印刷する場合
        loop 注文明細分
            pc -> pt: 単票印刷
        end
    end
    alt 複票印刷する場合
        pc -> pt: 複票印刷
    end
    pc -> b: 注文BoardObjectDelete
end

pc -> pc: subscribe

== Subscribe中のイベント ==

b -> pc: BoardObjectAddかつ、kitchen_statusがキャンセル以外
alt 単票印刷する場合
    loop 注文明細分
        pc -> pt: 単票印刷
    end
end
alt 複票印刷する場合
    pc -> pt: 複票印刷
end
pc -> b: 注文BoardObjectDelete

...

b -> pc: BoardObjectAddかつ、kitchen_statusがキャンセル
alt 単票印刷する場合
    loop 注文明細分
        pc -> pt: キャンセル単票印刷
    end
end
alt 複票印刷する場合
    pc -> pt: キャンセル複票印刷
end
pc -> b: 注文BoardObjectDelete
