title PrintControllerのみ使う場合

participant Board as b
participant PrintController as pc

pc -> pc: 端末起動

== 未印刷伝票印刷 ==
b -> pc: FetchBoard
pc -> pc: キャンセルされた注文を取得
note left
    ・kitchen_statusがcanceled
    ・pc_print_statusがcancel_printedでない注文を取得
end note
loop 注文分
    alt 単票印刷の場合
        pc -> pc: pr_print_statusがcancel_printedでない注文明細を取得
        loop 注文明細分
            pc -> pc: 印刷
            pc -> b: 注文明細のpc_print_statusにcancel_printedを入れてタグセット
            note right
                紙切れなど、途中で印刷が失敗しても良いように、
                印刷が終わった直後にそのBoardObjectにタグをセットする。
                全て印刷したら全ての明細分タグセットなどは行わない。
            end note
        end
    else 複票印刷の場合
        pc -> pc: 印刷
    end
    pc -> b: 注文のpc_print_statusにcancel_printedを入れてタグセット、かつDelete
end

pc -> pc: 伝票未印刷の注文を取得
note left
    ・kdの印刷タイミングを引き継ぐ、
    　　かつ「KDAppConfig.調理待ちで印刷する」がtrueの場合、
    　　kitchen_statusがwaiting
    ・kdの印刷タイミングを引き継ぐ、
    　　かつ「KDAppConfig.要調理で印刷する」がtrueの場合、
    　　kitchen_statusがcooking
    ・上記に当てはまり、かつpc_print_statusがnot_printed
end note
loop 注文分
    alt 単票印刷の場合
        pc -> pc: pc_print_statusがnot_printedの注文明細を取得
        loop 注文明細分
            pc -> pc: 印刷
            pc -> b: 注文明細のpc_print_statusにvoucher_printedを入れてタグセット
        end
    else 複票印刷の場合
        pc -> pc: 印刷
    end
    pc -> b: 注文のpc_print_statusにvoucher_printedを入れてタグセット
end

pc -> pc: subscribe

== kitchen_statusに更新がかかる ==
b -> pc: kitchen_statusタグにwaitingが入ってくる
alt kdの印刷タイミングを引き継ぐ、かつ「KDAppConfig.調理待ちで印刷する」がtrueの場合
    alt 単票印刷の場合
        loop 注文明細分
            pc -> pc: 印刷
            pc -> b: 注文明細のpc_print_statusにvoucher_printedを入れてタグセット
        end
    else 複票印刷の場合
        pc -> pc: 印刷
    end
    pc -> b: 注文のpc_print_statusにvoucher_printedを入れてタグセット
else kdの印刷タイミングを引き継がず、注文が入った直後に印刷する場合
    alt 単票印刷の場合
        loop 注文明細分
            pc -> pc: 印刷
            pc -> b: 注文明細のpc_print_statusにvoucher_printedを入れてタグセット
        end
    else 複票印刷の場合
        pc -> pc: 印刷
    end
    pc -> b: 注文のpc_print_statusにvoucher_printedを入れてタグセット
end

...

b -> pc: kitchen_statusタグにcookingが入ってくる
alt kdの印刷タイミングを引き継ぐ、かつ「KDAppConfig.要調理で印刷する」がtrueの場合
    alt 単票印刷の場合
        loop 注文明細分
            pc -> pc: 印刷
            pc -> b: 注文明細のpc_print_statusにvoucher_printedを入れてタグセット
        end
    else 複票印刷の場合
        pc -> pc: 印刷
    end
    pc -> b: 注文のpc_print_statusにvoucher_printedを入れてタグセット
end

...

b -> pc: kitchen_statusタグにcanceledが入ってくる
alt 単票印刷の場合
    loop 注文明細分
        pc -> pc: 印刷
        pc -> b: 注文明細のpc_print_statusにcancel_printedを入れてタグセット
    end
else 複票印刷の場合
    pc -> pc: 印刷
end
pc -> b: 注文のpc_print_statusにcancel_printedを入れてタグセット、かつDelete
