title KDとPCが共存する場合

participant Board as b
participant KD as k
participant PrintController as pc
participant プリンタ as pt

k -> k: 端末起動
k -> b: FetchBoard API
b -> k: BoardObjects
k -> k: 調理対象の注文を表示

pc -> pc: 端末起動

...

== 未印刷伝票印刷 ==
alt 「KDApptonfig.印刷機能を使う」がtrueの場合
    pc -> b: FetchBoard API
    b -> pc: BoardObjects
    pc -> pc: キャンセルされた注文を取得
    note left
        ・kitchen_statusがcanceled
        ・cancel_printed_atがない注文
    end note

    pc -> pc: 伝票未印刷の注文を取得
    note left
        ・「KDApptonfig.調理待ちで印刷する」がtrueの場合、
        　　kitchen_statusがwaitingかつ、waiting_printed_atがない。（そもそも印刷されてない）
        　　または、kitchen_statusがwaitingかつ、waiting_printed_atがある場合、
        　　端末のSQLiteにwaiting、かつそのboard_object_keyがない。（他端末で印刷されたが、その端末で印刷されていない）
        ・「KDApptonfig.要調理で印刷する」がtrueの場合、
        　　kitchen_statusがcookingかつ、cooking_printed_atがない。（そもそも印刷されてない）
        　　または、kitchen_statusがcookingかつ、cooking_printed_atがある場合、
        　　端末のSQLiteにcooking、かつそのboard_object_keyがない。（他端末で印刷されたが、その端末で印刷されていない）
    end note

    ...

    pc -> pc: 未印刷キャンセル伝票印刷
    loop 指定された未印刷キャンセル伝票分
        alt 単票印刷する場合
            loop 注文明細分
                pc -> pt: キャンセル単票印刷
            end
        end
        alt 複票印刷する場合
            pc -> pt: キャンセル複票印刷
        end
        pc -> pc: 端末内のSQLiteに印刷済みboard object key、調理ステータス入れる
        pc -> b: キャンセル注文のcancel_printed_atに現在日時を入れてタグセット
    end

    ...

    pc -> pc: 未印刷伝票印刷
    loop 指定された未印刷伝票分
        alt 単票印刷する場合
            loop 注文明細分
                pc -> pt: 単票印刷
            end
        end
        alt 複票印刷する場合
            pc -> pt: 複票印刷
        end
        pc -> pc: 端末内のSQLiteに印刷済みboard object key、調理ステータス入れる
        pc -> b: 注文の[KitchenStatus]_printed_atに現在日時を入れてタグセット
    end
end

pc -> pc: subscribe

...

== kitchen_statusに更新がかかる(A) ==
b -> pc: kitchen_statusタグのcancel以外の更新
alt 「KDApptonfig.印刷機能を使う」がtrueの場合
    alt 「KDApptonfig.[KitchenStatus]で印刷する」がtrueの場合
        alt 単票印刷する場合
            loop 注文明細分
                pc -> pt: 単票印刷
            end
        end
        alt 複票印刷する場合
            pc -> pt: 複票印刷
        end
        pc -> pc: 端末内のSQLiteに印刷済みboard object key、調理ステータス入れる
        pc -> b: 注文の[KitchenStatus]_printed_atに現在日時を入れてタグセット
    end
end

...

b -> pc: kitchen_statusタグにcanceledが入ってくる
alt 「KDApptonfig.印刷機能を使う」がtrueの場合
    alt 単票印刷する場合
        loop 注文明細分
            pc -> pt: キャンセル単票印刷
        end
    end
    alt 複票印刷する場合
        pc -> pt: キャンセル複票印刷
    end
    pc -> pc: 端末内のSQLiteに印刷済みboard object key、調理ステータス入れる
    pc -> b: 注文のcancel_printed_atに現在日時を入れてタグセット
    note right
        キャンセル後のDeleteは、スタッフのアクションによって行われるので、
        ここではDeleteしない
    end note
end

...

== Subscribe中にネットワーク切断 ==

... ネットワークが繋がる ...

pc -> b: FetchBoardを叩く
b -> pc: BoardObjects
pc -> pc: 未印刷伝票印刷時と同じ印刷処理
pc -> pc: subscribe

...

k -> b: お渡し完了日時タグセット & BoardObjectDelete
b -> k: BoardObjectDelete
k -> k: 調理一覧からDeleteされた注文を削除

...

k -> k: キャンセル注文消し込み
k -> b: BoardObjectDelete
b -> k: BoardObjectDelete
k -> k: キャンセル済み注文からDeleteされた注文を削除