title KDとPCが共存する場合

participant Board as b
participant KD as k
participant プリンタ as pt

k -> k: 端末起動
k -> b: FetchBoard API
b -> k: BoardObjects
k -> k: 調理対象の注文を表示

...

== 未印刷伝票印刷 ==
alt 「KDApptonfig.印刷機能を使う」がtrueの場合
    k -> b: FetchBoard API
    b -> k: BoardObjects
    k -> k: キャンセルされた注文を取得
    note left
        ・kitchen_statusがcanceled
        ・kd_cancel_print_statusがwaitingの注文を取得
    end note

    k -> k: 伝票未印刷の注文を取得
    note left
        ・「KDApptonfig.調理待ちで印刷する」がtrueの場合、
        　　kitchen_statusがwaitingかつ、kd_waiting_print_statusがwaiting
        ・「KDApptonfig.要調理で印刷する」がtrueの場合、
        　　kitchen_statusがcookingかつ、kd_cooking_print_statusがwaiting
    end note

    ...

    k -> k: 未印刷キャンセル伝票印刷
    loop 指定された未印刷キャンセル伝票分
        alt 単票印刷する場合
            loop 注文明細分
                k -> pt: キャンセル単票印刷
            end
        end
        alt 複票印刷する場合
            k -> pt: キャンセル複票印刷
        end
        k -> b: キャンセル注文のkd_cancel_print_statusにprintedを入れてタグセット
    end

    ...

    k -> k: 未印刷伝票印刷
    loop 指定された未印刷伝票分
        alt 単票印刷する場合
            loop 注文明細分
                k -> pt: 単票印刷
            end
        end
        alt 複票印刷する場合
            k -> pt: 複票印刷
        end
        k -> b: 注文のkd_[KitchenStatus]_print_statusにprintedを入れてタグセット
    end
end

k -> k: subscribe

...

== kitchen_statusに更新がかかる ==
b -> k: kitchen_statusタグのcancel以外の更新
alt 「KDApptonfig.印刷機能を使う」がtrueの場合
    alt 「KDApptonfig.[KitchenStatus]で印刷する」がtrueの場合
        alt 単票印刷する場合
            loop 注文明細分
                k -> k: 単票印刷
            end
        end
        alt 複票印刷する場合
            k -> k: 複票印刷
        end
        k -> b: 注文のkd_[KitchenStatus]_print_statusにprintedを入れてタグセット
    end
end

...

b -> k: kitchen_statusタグにcanceledが入ってくる
alt 「KDApptonfig.印刷機能を使う」がtrueの場合
        alt 単票印刷する場合
            loop 注文明細分
                k -> pt: キャンセル単票印刷
            end
        end
        alt 複票印刷する場合
            k -> pt: キャンセル複票印刷
        end
    k -> b: 注文のkd_cancel_print_statusにprintedを入れてタグセット
    note right
        キャンセル後のDeleteは、スタッフのアクションによって行われるので、
        ここではDeleteしない
    end note
end

...

k -> b: お渡し完了日時タグセット & BoardObjectDelete
b -> k: BoardObjectDelete
k -> k: 調理一覧からDeleteされた注文を削除

...

k -> k: キャンセル注文消し込み
k -> b: BoardObjectDelete
b -> k: BoardObjectDelete
k -> k: キャンセル済み注文からDeleteされた注文を削除