title 会計明細印刷

participant OderTable as ot
participant OderBE as o
participant Board as b

box "店内機器" #LightBlue
    participant PrintController as pc
    participant プリンタ as pt
end box

pc -> pc: 端末起動

== 未印刷会計明細印刷 ==

b <- pc: FetchBoard
b --> pc: 生きているBoardObject一覧

loop 全てのBoardObject
    pc -> pt: 会計明細印刷
    pc <-- pt: 成功
    b <- pc: BoardObjectDelete
    b --> pc: 成功
    o <- pc: 会計明細印刷完了通知
    o --> pc: 成功
end

b <-> pc: subscribe

== Subscribe中のイベント ==

ot -> o: 会計リクエスト
o -> b: 会計明細印刷Publish
b -> pc: 会計明細印刷Publish
b <-- pc: 成功
o <-- b: 成功
ot <-- o: 成功
pc -> pt: 会計明細印刷Publish
pc <-- pt: 成功
b <- pc: BoardObjectDelete
b --> pc: 成功
o <- pc: 会計明細印刷完了通知
note right
    伝票番号をkeyとして送る
end note
o --> pc: 成功

== ネットワーク切断がされた ==
pc -> b: FetchBoard
b --> pc: 現在のBoard内のBoardObject一覧
pc -> pc: 未印刷会計明細印刷時と同じ処理を行う
